apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
# endpoint and token are intentionally left empty
metadata:
  namespace: default
  name: qemu
endpoint: ""
#token: ""
export:
  shell:
    type: jumpstarter_driver_shell.driver.Shell
    config:
      methods:
        test-lola:
          command: |
            sshcmd() {
              sshpass -p 'password' ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 2222 root@localhost $@
            }

            sleep 10
            sshcmd 'cat /etc/os-release'
            sleep 10
            sshcmd 'bluechictl start agent-qm lola-ipc-sub.service'
            sleep 10
            sshcmd '/usr/bin/lola-ipc-test'
            echo $? > /tmp/jmp.rc.txt
  qemu:
    type: jumpstarter_driver_qemu.driver.Qemu
    config:
      cpu: host
      smp: 4
      mem: 2G
      default_partitions:
        # ubuntu
        OVMF_CODE.fd: /usr/share/OVMF/OVMF_CODE_4M.fd
        OVMF_VARS.fd: /usr/share/OVMF/OVMF_VARS_4M.fd
        # fedora and variants
        # OVMF_CODE.fd: /usr/share/OVMF/OVMF_CODE.fd
        # OVMF_VARS.fd: /usr/share/OVMF/OVMF_VARS.fd
      hostfwd:
        ssh:
          hostport: 2222
          guestport: 22
